#!/bin/bash

## Install Chocolatey
# https://chocolatey.org

## Install Cygwin (32-bit)
# choco install cygwin -x86
# add "call %HOME%\.startup.bat" to start of C:\tools\cygwin\Cygwin.bat
# mount -c /
# mount -m > /etc/fstab

## MinGW
# install MinGW compilers using mingw-get

## Install apt-cyg
# install wget with setup.exe
# wget https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg
# chmod +x apt-cyg
# mv apt-cyg /bin

## Install development tools
# choco install git
# apt-cyg install gcc-core gcc-g++
# apt-cyg install make
# apt-cyg install openssh

## Install virtual machines
# choco install vagrant
# choco install virtualbox
# vagrant plugin install vagrant-vbguest

net session &>/dev/null
if [ $? -ne 0 ]; then
    echo "Must be root"
    exit 1
fi

if [[ "$CYGWIN" != *winsymlinks:native* ]]; then
    echo "winsymlinks:native must be in \$CYGWIN"
    exit 1
fi

echo "
export EMACS=/c/ProgramData/chocolatey/bin/emacs
export EMACS_CLIENT=\"emacsclient -a runemacs.exe\"
source $HOME/xdots/bashrc
" > "$HOME/.profile"

source "$HOME/.profile"
xdots_setup
