#!/bin/bash

# https://chocolatey.org
# choco install cygwin
# choco install git
# choco install vagrant
# choco install virtualbox
# choco install openssh
# vagrant plugin install vagrant-vbguest
# add "call %HOME%\.startup.bat" to start of C:\Cygwin\Cygwin.bat

net session &>/dev/null
if [ $? -ne 0 ]; then
    echo "Must be root"
    exit 1
fi

if [[ "$CYGWIN" != *winsymlinks:native* ]]; then
    echo "winsymlinks:native must be in \$CYGWIN"
    exit 1
fi

echo "
export EMACS=/cygdrive/c/ProgramData/chocolatey/bin/emacs
export EMACS_CLIENT=\"emacsclient -a runemacs.exe\"
source $HOME/xdots/bashrc
" > "$HOME/.profile"

source "$HOME/.profile"
xdots_setup
