#!/bin/bash

## Install Cygwin (+ wget)
# install apt-cyg
# apt-cyg install openssh git
# add "call C:\Users\xmasotto\.startup.bat" to start of C:\cygwin\Cygwin.bat
# mount -c /
# mount C:\Users /home
# mount -m > /etc/fstab

## Install MinGW
## Install MSYS2
## Install Chocolatey
## Install emacs (via choco)

## Install virtual machines
# choco install vagrant
# choco install virtualbox
# vagrant plugin install vagrant-vbguest

net session &>/dev/null
if [ $? -ne 0 ]; then
    echo "Must be root"
    exit 1
fi

if [[ "$CYGWIN" != *winsymlinks:native* ]]; then
    echo "winsymlinks:native must be in \$CYGWIN"
    exit 1
fi

echo "
export EMACS=/c/ProgramData/chocolatey/bin/emacs
export EMACS_CLIENT=\"emacsclient -a runemacs.exe\"
source $HOME/xdots/bashrc
" > "$HOME/.profile"

source "$HOME/.profile"
xdots_setup
