#!/bin/bash

source "$HOME/xdots/bashrc"
xdots_setup

cd "`dirname \"$0\"`"
scripts_path="`readlink -f ./conf_.scripts`"

echo "export PATH=$scripts_path:"'$PATH' > /tmp/xdots.sh
sudo mv /tmp/xdots.sh /etc/profile.d
