#!/bin/bash

brew install git
brew install coreutils --default-names
brew install findutils --default-names
brew install gnu-tar --default-names
brew install gnu-sed --default-names
brew install --cocoa emacs

echo "
PATH=/usr/local/opt/coreutils/libexec/gnubin:\$PATH
PATH=/usr/local/opt/gnu-tar/libexec/gnubin:\$PATH
PATH=/usr/local/opt/gnu-sed/bin:\$PATH
source $HOME/xdots/bashrc

EMACS_SERVER='/usr/local/Cellar/emacs/24.3/Emacs.app/Contents/MacOS/Emacs --daemon'
EMACS_CLIENT='/usr/local/Cellar/emacs/24.3/bin/emacsclient -nw'
" > "$HOME/.profile"

source "$HOME/.profile"
xdots_setup
