#!/bin/bash
cd ~ &&
wget https://github.com/xmasotto/xdots/archive/master.zip -O xdots.zip &&
unzip xdots.zip &&
rm xdots.zip &&
mv xdots-master xdots &&
. xdots/bashrc &&
xdots_setup &&
. xdots/bashrc
