#!/bin/bash

source ~/.bashrc.d/emacs

# Delete the old server, if it exists.
demacs

# Start a new server.
/usr/bin/emacs --daemon || exit

# Initialize the inferior shells.
emacsclient -ce "(setup-shells)"

if [ "$emacs_pid" ]; then
  echo "Successfully restarted emacs server."
else
  echo "Sucessfully started emacs server."
fi
