#!/bin/bash

# Don't try to page the output if in emacs
if [ "$INSIDE_EMACS" ]; then
  tmp_file="$HOME/.emacs_pager_tmp"
  cat $* | col -b > "$tmp_file"
  emacs "$tmp_file"
  rm "$tmp_file"
else
  less $*
fi