#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 PROGRAM ARGS"
fi

program="$1"
shift

echo "
set \$_exitcode = -999
r $*
if \$_exitcode != -999
  quit
end
" > .debug_tmp

gdb "$program" -x .debug_tmp
rm .debug_tmp
