#!/bin/bash
if [ $# -lt 1 ]; then
    echo "Usage: $0 filename"
    exit 1
fi

f="$1"
function subs {
  echo "$f" | sed "s/tex/$1/g"
}

pdflatex "$1";
compiled="$?"

subs log | xargs rm -f &&
subs out | xargs rm -f &&
subs aux | xargs rm -f &&
subs dvi | xargs rm -f &&
rm -f texput.log

if [ "$compiled" -eq "0" ]; then
    (subs pdf | xargs evince &>/dev/null &)
fi
