#!/bin/bash
source ~/.bashrc.d/util

[ -z "$USE_GNOME_SCREENSAVER" ] && USE_GNOME_SCREENSAVER=false

if [ "$USE_GNOME_SCREENSAVER" == "true" ]; then
  gnome-screensaver-command --lock
  exit
else
  # Kill the gnome screensaver process if it is running.
  gnome_pid="`ps aux | grep 'gnome-screensaver' | filter_pids`"
  if [ "$gnome_pid" ]; then
    kill $gnome_pid
  fi

  # Start the xscreensaver process if it isn't already running.
  xscreen_pid="`ps aux | grep 'xscreensaver' | filter_pids`"
  if [ -z "$xscreen_pid" ]; then
    xscreensaver -nosplash &
  fi

  # Lock the computer.
  xscreensaver-command --lock
fi