#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 CLASS"
    exit
fi

svn checkout "https://subversion.ews.illinois.edu/svn/$1/masotto2" --username masotto2
if [ $2 ]; then
    mv masotto2 "$2"
fi
