#!/bin/bash

DNS_SERVER="`[ -f \"$HOME/.dns_server\" ] && cat \"$HOME/.dns_server\"`"
DNS_NAME="`[ -f \"$HOME/.dns_name\" ] && cat \"$HOME/.dns_name\"`"

if [ -z "$DNS_SERVER" ]; then
    echo "Set your nameserver hostname in ~/.dns_server."
    exit 1
fi

if [ -z "$DNS_NAME" ]; then
    echo "Set your subdomain name in ~/.dns_name."
    exit 1
fi

nopass=""
if [ "$1" ] && [ "$1" == "nopass" ]; then
    nopass="1"
fi

ip="`get_ip`"
host_ip="`host $DNS_NAME.$DNS_SERVER | cut -d" " -f4`"

[ "$ip" != "$host_ip" ] &&
echo "==============================" &&
echo "* `date`" &&
ssh `[ "$nopass" ] && echo -oBatchMode=yes` \
    -oStrictHostKeyChecking=no \
    xmasotto@$DNS_SERVER "~/dns/update_dns $DNS_NAME `get_ip`" &&
host "$DNS_NAME.$DNS_SERVER"


