#!/bin/bash

PS1="[\[\e[0;33m\]\u\[\e[m\]::\[\e[0;35m\]\h\[\e[m\] \[\e[1;34m\]\W\[\e[m\]] $ "
if [ "$INSIDE_EMACS" ]; then
  PS1="|PROMPT|\w|$PS1"
fi

if [ -z "$_first_time" ]; then
    ORIGINAL_PATH_="$PATH"
    _first_time=1
fi

# easy source, resets path variables first
function s {
    for v in $(set | grep '^\w*PATH$' | cut -d= -f1); do
		unset $v
    done
    export PATH="$ORIGINAL_PATH_"
	unalias -a
	source ~/xdots/bashrc
}

# colors
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# emacs is my life
export EDITOR="emacs"

# History
function hist {
    history ${1-10} | sed 's/^[ ]*[0-9]*[ ]*\(.*\)$/\1/g'
}

# Tags
function tag {
	rm /tmp/files_to_tag
	for ext in $*; do
		find . -name "*.$ext" >> /tmp/files_to_tag
	done
	etags - < /tmp/files_to_tag
}

alias msbuild="msbuild.exe"

function mingw {
	if [ -z "$(echo $PS1 | grep '(mingw)')" ]; then
		rm -rf ~/mingw_bin
		mkdir -p ~/mingw_bin

		export PATH="/c/mingw/bin:$PATH"
		export PATH="/c/msys64/usr/bin:$PATH"

		PS1="(mingw)$PS1"
		function msys {
			bash -c "$*"
		}
		function pacman {
			msys pacman $*
		}
	fi
}

if [ "$(uname -o)" == "Cygwin" ]; then
	export PYTHONPATH=$(cygpath -p "$PYTHONPATH" 2>/dev/null)
	unset PYTHONHOME
fi
