#!/bin/bash
source ~/.bashrc.d/util

export EMACS_SERVER=${EMACS_SERVER:-/usr/bin/emacs --daemon}

export EMACS_CLIENT=${EMACS_CLIENT:-/usr/bin/emacsclient}
EMACS_CLIENT="$EMACS_CLIENT --socket-name=/tmp/emacs$UID/server"

function emacs_server_process() {
    ps wwaux | grep "$EMACS_SERVER" | grep -v 'grep'
}

function emacs_server_pid() {
    arg_list "`emacs_server_process | filter_pids`"
}

function emacs_client_processes() {
    ps wwaux | grep $EMACS_CLIENT | grep -v 'grep'
}

function emacs_client_pids() {
    arg_list "`emacs_client_processes | filter_pids`"
}

function el {
    emacsclient -e "$*" | sed -e 's/^"\(.*\)"$/\1/g' \
	-e 's/\\n/\n/g' \
	-e 's/\\"/"/g' \
	-e 's/\\\\/\\/g'
}

function ehist {
    el '(minibuffer-shell-history)' | tail -n ${1-10}
}

function cask {
    EMACS=$(echo $EMACS_SERVER | cut -d' ' -f1) $(which cask) $@
}
