#!/bin/bash

function ssh2_add {
    file="$HOME/xdots/conf_.bashrc.d/_quick_ssh_data"
    if [ $# -ne 2 ]; then
	echo "Usage: ssh2_add NAME HOSTNAME"
	return
    fi
    echo "alias $1=\"echo $2\"" >> $file
    s
}

function ssh2 {
    host="`eval $1`" && ssh "$host"
}

function scp2_translate {
    name=`echo $1 | sed -n 's/\(\w*\):.*/\1/p'`
    if [ "$name" ]; then
	translated="`eval $name`" &&
	echo $1 | sed "s/$name/$translated/g"
    else
	echo $1
    fi
}

function scp2 {
    if [ $# -ne 2 ]; then
	echo "Usage: scp2 FILE1 FILE2"
	return
    fi
    arg1="`scp2_translate $1`" &&
    arg2="`scp2_translate $2`" &&
    scp -r "$arg1" "$arg2"
}

function sync2 {
    if [ $# -ne 1 ]; then
	echo "Usage: sync2 DEST"
	return
    fi
    changed="$(git diff --name-only HEAD)"
    if [[ $? && "$changed" ]]; then
	scp2 $changed $1/
    fi
}
