#!/bin/bash

function ssh2_add {
    file="$HOME/xdots/conf_.bashrc.d/_quick_ssh_data"
    if [ $# -ne 2 ]; then
	echo "Usage: ssh2_add NAME HOSTNAME"
	return
    fi
    echo "alias $1=\"echo $2\"" >> $file
    s
}

function ssh2 {
    host="`eval $1`" && ssh "$host"
}

function scp2_translate {
    name=`echo $1 | sed -n 's/\(\w*\):.*/\1/p'`
    if [ "$name" ]; then
	translated="`eval $name`" &&
	echo $1 | sed "s/$name/$translated/g"
    else
	echo $1
    fi
}

function scp2 {
    if [ $# -lt 2 ]; then
	echo "Usage: scp2 [SRC ...] DEST"
	return
    fi

    scp_args=""
    for file in $@; do
	scp_args="$scp_args $(scp2_translate $file)"
    done
    scp -r $scp_args
}

function sync2 {
    OPTIND=
    SYNC_ALL=
    while getopts "a" OPTION; do
	case $OPTION in
	    a) SYNC_ALL=1
		;;
	esac
    done
    shift $(($OPTIND - 1))

    if [ $# -ne 1 ]; then
	echo "Usage: sync2 DEST"
	return
    fi

    if [ "$SYNC_ALL" ]; then
	changed="$(git ls-tree -r --name-only --full-tree HEAD)"
    else
	changed="$(git diff --name-only HEAD)"
    fi

    if [[ $? && "$changed" ]]; then
	(cd "$(git rev-parse --show-toplevel)"
	    for file in $changed; do
		target=".tmp/$(dirname $file)"
		mkdir -p $target
		cp $file $target
	    done
	    scp2 .tmp/* $1/
	    rm -rf .tmp)
    fi
}
